version: "2.1"
services:
  memcached:
    image: registry.opensuse.org/opensuse/memcached:latest
  database:
    image: registry.opensuse.org/opensuse/postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: mysecretpassword
  software:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        CONTAINER_USERID: 1000
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/software
    ports:
      - "3000:3000"
    depends_on:
      - memcached
      - database
    environment:
      - MEMCACHED_HOST="memcached:11211"
