defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  host: <%= ENV.fetch('SOFTWARE_DB_HOST', 'database') %>
  port: <%= ENV.fetch('SOFTWARE_DB_PORT', '5432')  %>
  username: <%= ENV.fetch('SOFTWARE_DB_USER', 'postgres') %>
  password: <%= ENV.fetch('SOFTWARE_DB_PASSWORD', 'mysecretpassword') %>
  database: <%= ENV.fetch('SOFTWARE_DB_NAME', 'postgres') %>

development:
  <<: *defaults
  database: software_development

test:
  <<: *defaults
  database: software_test

production:
  <<: *defaults
  # no defaults for host/port as we might want to connect through a socket
  host: <%= ENV.fetch('SOFTWARE_DB_HOST', nil) %>
  port: <%= ENV.fetch('SOFTWARE_DB_PORT', nil)  %>
  database: software_production
