#!/usr/bin/ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require File.join(RAILS_ROOT, 'lib/workers/search_helper_job.rb')
require 'delayed/command'
require 'app/helpers/search_helper'
Delayed::Command.new(ARGV).daemonize

